// Assuming `api` is the setup from "@reduxjs/toolkit/query/react"
import { api } from "../../app/api";

// Define a new API slice specifically for user-related operations
export const userApi = api.injectEndpoints({
  endpoints: (builder) => ({
    getAccountDetails: builder.query({
      query: () => {
        // Assuming you're managing the token in localStorage or a similar strategy
        const token = localStorage.getItem("bearerToken");

        return {
          url: "users/me", // Adjust this URL based on your backend endpoint
          method: "GET",
          headers: {
            Authorization: `Bearer ${token}`,
          },
        };
      },
      // Optional: Define tags for cache control, if needed
      providesTags: ['UserDetails'],
    }),
  }),
  overrideExisting: false, // Set to true if you're redefining an existing endpoint
});

// Export the hook generated by RTK Query
export const { useGetAccountDetailsQuery } = userApi;